### ISSUE TITLE
GameCube Controller 'Y' button detection not working

### ISSUE THREAD

**Issue by GoogleSerg** [sctech-tr/tbct-wii#1]
Hello. 
Noticed when using the software that the 'Y' button on the GameCube never gets detected by the software. I checked the source and noticed there's no code for indicating when the 'Y' button is pressed on the GameCube Controller.

**Comment by sctech-tr** [comment]
***TLDR: fixing rn, reinstall the new version (v1.3) when it releases. thanks for informing!***

First of all, thanks for reporting a bug and making the software great for everyone. (i also appreciate someone finally using apps i made)

I do mess up code sometimes, like forgetting to scan the wiimote before trying to detect which button is clicked

I'm fixing it now, and you can install v1.3 when it's out! Thanks again for informing!

**Comment by sctech-tr** [comment]
It should be fixed by now @GoogleSerg

**Comment by GoogleSerg** [comment]
A pleasure! Thx for making useful apps!
